### ISSUE TITLE
Error for filterByCurrency in MoneyUtil

### ISSUE THREAD

**Issue by bokherus** [OOP2018/coinpurse-Driveiei#3]
<img width="531" alt="screen shot 2561-01-24 at 12 46 08 am" src="https://user-images.githubusercontent.com/9125776/35291546-2d971d5c-00a0-11e8-91e5-f309d6dfde51.png">

**Comment by Driveiei** [comment]
@bokherus Can you tell me what's bug in that's method ? I don't see it. T.T
