### ISSUE TITLE
filterByCurrency should not modify money

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-Driveiei#4]
https://github.com/OOP2018/coinpurse-Driveiei/blob/c6eb3efcee276f4738a868adf39cfb98e126a6e7/src/coinpurse/MoneyUtil.java#L114-L116

**Comment by taveratch** [comment]
https://github.com/OOP2018/coinpurse-Driveiei/blob/14b88e0682e3a28fee4535635e33738436c1e106/src/coinpurse/MoneyUtil.java#L117
The easier way would just return the same currency. 
Nothing is wrong with your code but it's doing in the opposite direction.

**Comment by Driveiei** [comment]
@taweesoft Thanks for your advice. I will fixed today :)
