### ISSUE TITLE
Logic explanation

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-Driveiei#8]
How could `this.getValue() - getValue()` is not zero?

https://github.com/OOP2018/coinpurse-Driveiei/blob/0ab45c241a25ff4529918461cedbaabcbe6f3b26/src/coinpurse/Coin.java#L27-L31

**Comment by Driveiei** [comment]
value is double so, (int) this.getValue()  makes double to int then if the value have decimal like 12.25 , It's will be 12. Therefore, It will not be zero.
